import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

import { Amplify } from "aws-amplify";
import amplifyconfig from "../amplifyconfiguration.json";
Amplify.configure(amplifyconfig);

// import { withAuthenticator, Button, Heading } from "@aws-amplify/ui-react";
// import "@aws-amplify/ui-react/styles.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
